import React, { useState } from 'react';
import { Form, Button, Card, Row, Col } from 'react-bootstrap';
import type { ObservationType } from '../types/types';
import { useNavigate } from 'react-router-dom';
import {useQuestionValues, type QuestionState} from '../FormContext.tsx'

interface AdditionFormProps {
  addObservation: (content: ObservationType) => Promise<void>;
}

const AdditionForm: React.FC<AdditionFormProps> = ({ addObservation }) => {
  const [observation, setObservation] = useState<ObservationType>({
    id: 0, // should be generated by backend
    scientific_name: '',
    common_name: '',
    description: '',
    date: '',
    location: '',
    image: ''
  });

  const [validated, setValidated] = useState(false);
  const navigate = useNavigate()
  const questionAnswers: QuestionState = useQuestionValues()

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = event.currentTarget;
    
    if (form.checkValidity() === false) {
      event.stopPropagation()
      setValidated(true)
    } else {
      // Form is valid - handle submission
      addObservation(observation)

      // Reset form
      setObservation({
        id: 0,
        scientific_name: '',
        common_name: '',
        description: '',
        date: '',
        location: '',
        image: ''
      });

      setValidated(false)

      navigate('/')
    }
  
  };

  const handleInputChange = (field: keyof ObservationType, value: string) => {
    setObservation(prev => ({
      ...prev,
      [field]: value
    }));
  };

  return (
    <Card className="p-4">
      <Card.Body>
        <Card.Title className="mb-4">Add New Observation</Card.Title>
        <Form noValidate validated={validated} onSubmit={handleSubmit}>

          {!questionAnswers.identification &&
            <Row>
            <Col md={6}>
              <Form.Group className="mb-3">
                <Form.Label>Scientific Name *</Form.Label>
                <Form.Control
                  type="text"
                  placeholder="Enter scientific name"
                  value={observation.scientific_name}
                  onChange={(e) => handleInputChange('scientific_name', e.target.value)}
                  required
                />
                <Form.Control.Feedback type="invalid">
                  Please provide a scientific name.
                </Form.Control.Feedback>
              </Form.Group>
            </Col>
            
            <Col md={6}>
              <Form.Group className="mb-3">
                <Form.Label>Common Name *</Form.Label>
                <Form.Control
                  type="text"
                  placeholder="Enter common name"
                  value={observation.common_name}
                  onChange={(e) => handleInputChange('common_name', e.target.value)}
                  required
                />
                <Form.Control.Feedback type="invalid">
                  Please provide a common name.
                </Form.Control.Feedback>
              </Form.Group>
            </Col>
          </Row>
          }

          <Form.Group className="mb-3">
            <Form.Label>Description *</Form.Label>
            <Form.Control
              as="textarea"
              rows={3}
              placeholder="Enter detailed description"
              value={observation.description}
              onChange={(e) => handleInputChange('description', e.target.value)}
              required
            />
            <Form.Control.Feedback type="invalid">
              Please provide a description.
            </Form.Control.Feedback>
          </Form.Group>

          <Row>
            <Col md={6}>
              <Form.Group className="mb-3">
                <Form.Label>Date of Observation *</Form.Label>
                <Form.Control
                  type="date"
                  value={observation.date}
                  onChange={(e) => handleInputChange('date', e.target.value)}
                  required
                />
                <Form.Control.Feedback type="invalid">
                  Please select a date.
                </Form.Control.Feedback>
              </Form.Group>
            </Col>
            
            {!questionAnswers.domestic &&
            <Col md={6}>
              <Form.Group className="mb-3">
                <Form.Label>Location *</Form.Label>
                <Form.Control
                  type="text"
                  placeholder="Enter location"
                  value={observation.location}
                  onChange={(e) => handleInputChange('location', e.target.value)}
                  required
                />
                <Form.Control.Feedback type="invalid">
                  Please provide a location.
                </Form.Control.Feedback>
              </Form.Group>
            </Col>
    }
          </Row>

          <Form.Group className="mb-4">
            <Form.Label>Image URL (Optional)</Form.Label>
            <Form.Control
              type="url"
              placeholder="https://example.com/image.jpg"
              value={observation.image}
              onChange={(e) => handleInputChange('image', e.target.value)}
            />
            <Form.Text className="text-muted">
              Provide a URL to an image of your observation
            </Form.Text>
          </Form.Group>

          <div className="d-grid gap-2 d-md-flex justify-content-md-end">
            <Button 
              variant="outline-secondary" 
              type="button"
              onClick={() => {
                setObservation({
                  id: 0,
                  scientific_name: '',
                  common_name: '',
                  description: '',
                  date: '',
                  location: '',
                  image: ''
                });
                setValidated(false);
              }}
            >
              Clear Form
            </Button>
            <Button variant="primary" type="submit">
              Submit Observation
            </Button>
          </div>
        </Form>
      </Card.Body>
    </Card>
  );
};

export default AdditionForm;