import React, { useState } from 'react';
import { Form, Button, Card, Row, Col, OverlayTrigger, Tooltip } from 'react-bootstrap';
import { MapContainer, TileLayer, Marker } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import type { ObservationType, DiscoveryType} from '../types/types';
import { useNavigate } from 'react-router-dom';
import {useQuestionValues, type QuestionState} from '../FormContext.tsx'
import helperFunctions from '../utils/helperFunctions.ts'
import { IoIosAddCircle } from "react-icons/io";
import { FiAlertCircle } from "react-icons/fi";
import { IoMdArrowRoundBack } from "react-icons/io";

interface AdditionFormProps {
  addObservation: (content: ObservationType) => Promise<void>;
}

const AdditionForm: React.FC<AdditionFormProps> = ({ addObservation }) => {
  // this is in itial state, but will be updated when user fills the form
  const [observation, setObservation] = useState<ObservationType>({
    id: 0, // should be generated by backend
    scientific_name: '',
    common_name: '',
    description: '',
    date: helperFunctions.getTodayDate(),
    location: '',
    coordinates: undefined,
    images: [],
    public: false,
    identified: false,
    category: 'fauna',
    discovery: 'domestic'
  });
  const [imagePreviews, setImagePreviews] = useState<string[]>(observation.images);
  const [selectedFiles, setSelectedFiles] = useState<File[]>([]);  // TODO: needed to upload actual files later
  const [validated, setValidated] = useState(false);
  const navigate = useNavigate()
  const questionAnswers: QuestionState = useQuestionValues()

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = event.currentTarget;
    
    if (form.checkValidity() === false) {
      event.stopPropagation()
      setValidated(true)
    } else {
      // Form is valid - handle submission
      const observationToSubmit = {...observation, 
        identified: questionAnswers.identification? false : true, 
        public: questionAnswers.public? true : false, 
        discovery: questionAnswers.domestic? 'domestic' : 'wildlife' as DiscoveryType
      }

      //console.log('Prepared observation for submission:', observationToSubmit);
      
      addObservation(observationToSubmit)

      clearAllPreviews();

      // Reset form
      setObservation({
        id: 0,
        scientific_name: '',
        common_name: '',
        description: '',
        date: '',
        location: '',
        coordinates: undefined,
        images: [],
        public: false,
        identified: false,
        category: 'fauna',
        discovery: 'domestic'
      });

      setValidated(false)

      navigate('/')
    }
  
  };

  const handleInputChange = (field: keyof ObservationType, value: string) => {
    setObservation(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files || files.length === 0) return;

    // revoke previous previews
    imagePreviews.forEach(url => URL.revokeObjectURL(url));
    
    const fileArray = Array.from(files);
    const urls: string[] = fileArray.map(f => URL.createObjectURL(f));

    setImagePreviews(urls);
    setSelectedFiles(fileArray);

    // store preview urls in observation so other components can render them
    setObservation(prev => ({ ...prev, images: urls }));  //TODO: check this
  };

  // Mini map marker component for draggable marker
  const DraggableMarker: React.FC<{ position: [number, number] | null }> = ({ position }) => {
    if (!position) return null;

    const eventHandlers = {
      dragend(e: any) {
        const marker = e.target;
        const latLng = marker.getLatLng();
        const lat = Number(latLng.lat);
        const lng = Number(latLng.lng);
        setObservation(prev => ({ ...prev, coordinates: { lat, lng }, location: `${lat.toFixed(6)}, ${lng.toFixed(6)}` }));
      }
    };

    return <Marker position={position} draggable eventHandlers={eventHandlers} />;
  };

  const handleRemovePreview = (index: number) => {
    const urlToRemove = imagePreviews[index];
    if (urlToRemove) {
      URL.revokeObjectURL(urlToRemove);
    }
    const newPreviews = imagePreviews.filter((_, i) => i !== index);
    setImagePreviews(newPreviews);
    // remove corresponding file from selectedFiles as well
    setSelectedFiles(prevFiles => prevFiles.filter((_, i) => i !== index));
    setObservation(prev => ({ ...prev, images: newPreviews }));
  };

  const clearAllPreviews = () => {
    imagePreviews.forEach(url => URL.revokeObjectURL(url));
    setImagePreviews([]);
    setSelectedFiles([]);
    setObservation(prev => ({ ...prev, images: [] }));
  };
  const miniMapCenter: [number, number] = [60.184230669318474, 24.83009157017735];
  return (
    <Card className="p-4">
      <Card.Body>
        <Row className="mb-3 align-items-center">
          <Col>
            <Card.Title className="mb-0">Add Observation</Card.Title>
          </Col>
          <Col xs="auto">
            <Button
              variant="link"
              onClick={() => navigate(-1)}
              aria-label="Go back"
              title="Go back"
              className="p-0"
            >
              <IoMdArrowRoundBack size={25} />
            </Button>
          </Col>
        </Row>
        <Row className="mb-5 g-1"> 
          {questionAnswers.domestic ? 
            <OverlayTrigger
              placement="bottom"
              overlay={<Tooltip>This is a domestic observation</Tooltip>}
            >
              <Col xs="auto" className="pe-2"> <IoIosAddCircle /> domestic </Col>
            </OverlayTrigger> : 
            <OverlayTrigger
              placement="bottom"
              overlay={<Tooltip>This is a wildlife observation</Tooltip>}
            >
              <Col xs="auto" className="pe-2"> <IoIosAddCircle /> wildlife </Col>
            </OverlayTrigger>
          }
          {questionAnswers.public ? 
            <OverlayTrigger
              placement="bottom"
              overlay={<Tooltip>This is a public observation</Tooltip>}
            >
              <Col xs="auto" className="pe-3"> <IoIosAddCircle /> public </Col> 
            </OverlayTrigger> : 
            <OverlayTrigger
              placement="bottom"
              overlay={<Tooltip>This is a private observation</Tooltip>}
            >
              <Col xs="auto" className="pe-3"> <IoIosAddCircle /> private </Col>
            </OverlayTrigger>
            }
          {questionAnswers.identification ? 
            <OverlayTrigger
              placement="bottom"
              overlay={<Tooltip>Identification help requested</Tooltip>}
            >
              <Col xs="auto" className="pe-2"> <FiAlertCircle /> </Col> 
            </OverlayTrigger> : 
            <Col xs="auto" className="pe-2">  </Col>
          }
        </Row>
        <Form noValidate validated={validated} onSubmit={handleSubmit}>
          <Row>
            <Col md={6}>
              <Form.Group className="mb-3">
                <Form.Label>Category of Observation *</Form.Label>
                  <Form.Select
                    value={observation.category}
                    onChange={(e) => handleInputChange('category', e.target.value)}
                    required
                    >
                    <option value="fauna">Fauna</option>
                    <option value="flora">Flora</option>
                    <option value="funga">Funga</option>
                </Form.Select>
                <Form.Control.Feedback type="invalid">  
                  Please select a category.
                </Form.Control.Feedback>
              </Form.Group>
            </Col>   
            <Col md={6}>
              <Form.Group className="mb-3">
                <Form.Label>Date of Observation *</Form.Label>
                <Form.Control
                  type="date"
                  value={observation.date}
                  onChange={(e) => handleInputChange('date', e.target.value)}
                  required
                />
                <Form.Control.Feedback type="invalid">
                  Please select a date.
                </Form.Control.Feedback>
              </Form.Group>
            </Col> 
          </Row>
          {!questionAnswers.identification &&
            <Row>
            <Col md={6}>
              <Form.Group className="mb-3">
                <Form.Label>Scientific Name *</Form.Label>
                <Form.Control
                  type="text"
                  placeholder="Enter scientific name"
                  value={observation.scientific_name}
                  onChange={(e) => handleInputChange('scientific_name', e.target.value)}
                  required
                />
                <Form.Control.Feedback type="invalid">
                  Please provide a scientific name.
                </Form.Control.Feedback>
              </Form.Group>
            </Col>
            
            <Col md={6}>
              <Form.Group className="mb-3">
                <Form.Label>Common Name *</Form.Label>
                <Form.Control
                  type="text"
                  placeholder="Enter common name"
                  value={observation.common_name}
                  onChange={(e) => handleInputChange('common_name', e.target.value)}
                  required
                />
                <Form.Control.Feedback type="invalid">
                  Please provide a common name.
                </Form.Control.Feedback>
              </Form.Group>
            </Col>
          </Row>
          }

          <Form.Group className="mb-3">
            <Form.Label>Description (Optional)</Form.Label>
            <Form.Control
              as="textarea"
              rows={3}
              placeholder="Enter detailed description"
              value={observation.description}
              onChange={(e) => handleInputChange('description', e.target.value)}
            />
            <Form.Control.Feedback type="invalid">
              Please provide a description.
            </Form.Control.Feedback>
          </Form.Group>

          <Row>
            {!questionAnswers.domestic &&
            <Col md={6}>
              <Form.Group className="mb-3">
                <Form.Label>Location *</Form.Label>
                <Form.Control
                  type="text"
                  placeholder="Enter coordinates"
                  value={observation.location}
                  onChange={(e) => handleInputChange('location', e.target.value)}
                  required
                />
                <Form.Control.Feedback type="invalid">
                  Please provide a location.
                </Form.Control.Feedback>
                <div className="mt-2" style={{ height: 300 }}>
                  <MapContainer center={miniMapCenter} zoom={13} style={{ height: '100%', width: '100%', borderRadius: 8 }}>
                    <TileLayer
                      attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
                      url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                    />
                    <DraggableMarker position={observation.coordinates ? [observation.coordinates.lat, observation.coordinates.lng] : miniMapCenter} />
                  </MapContainer>
                </div>
              </Form.Group>
            </Col>
          }
          </Row>
           <Form.Group className="mb-4">
            <Form.Label>Images</Form.Label>
            <Form.Control
              type="file"
              accept="image/*"
              multiple
              onChange={handleFileChange}
            />
            <Form.Text className="text-muted">
              Upload one or more images (previews will show below).
            </Form.Text>

            {imagePreviews.length > 0 && (
              <div className="mt-3 d-flex flex-wrap gap-2">
                {imagePreviews.map((src, idx) => (
                  <div key={src} style={{ position: 'relative' }}>
                    <img
                      src={src}
                      alt={`preview-${idx}`}
                      className="img-thumbnail"
                      style={{ width: 260, height: 260, objectFit: 'cover', borderRadius: 8 }}
                    />
                    <button
                      type="button"
                      onClick={() => handleRemovePreview(idx)}
                      style={{
                        position: 'absolute',
                        top: 4,
                        right: 4,
                        background: 'rgba(0,0,0,0.6)',
                        border: 'none',
                        color: 'white',
                        borderRadius: 12,
                        width: 24,
                        height: 24,
                        lineHeight: 0,
                        cursor: 'pointer'
                      }}
                      aria-label={`Remove image ${idx + 1}`}
                    >
                      ×
                    </button>
                  </div>
                ))}
              </div>
            )}
          </Form.Group>



        {/*
          <Form.Group className="mb-4">
            <Form.Label>Image URL *</Form.Label>
            <Form.Control
              type="url"
              placeholder="https://example.com/image.jpg"
              value={observation.image}
              onChange={(e) => handleInputChange('image', e.target.value)}
            />
            <Form.Text className="text-muted">
              Provide a URL to an image of your observation
            </Form.Text>
          </Form.Group>
        */}
          <div className="d-grid gap-2 d-md-flex justify-content-md-end">
            <Button 
              variant="outline-secondary" 
              type="button"
              onClick={() => {
                setObservation({
                  id: 0,
                  scientific_name: '',
                  common_name: '',
                  description: '',
                  date: '',
                  location: '',
                  images: [],
                  public: false,
                  identified: false,
                  category: 'fauna',
                  discovery: 'domestic'
                });
                setValidated(false);
              }}
            >
              Clear Form
            </Button>
            <Button variant="primary" type="submit">
              Submit Observation
            </Button>
          </div>
        </Form>
      </Card.Body>
    </Card>
  );
};

export default AdditionForm;